### ISSUE TITLE
Coping with Multiple Versions of Bible

### ISSUE THREAD

**Issue by Oblique82** [kuchejak/obsidian-bible-linker-plugin#13]
Some people have multiple versions of the bible stored

Is there any way to have this tool "choose" which one to use? eg specify a folder?

**Comment by kuchejak** [comment]
Hi, as of right now there is no direct way to use more than one version of bible. Only possible solution I can think of is to use different naming conventions for the books. 

It is a good feature, so I may add some kind of support for it later (I don't have time to work on it now, sorry).

**Comment by jakepog** [comment]
A way around multiple folders is I have multiple versions in a single text file, separated by headers into sections then with version added to each verse eg. ##### v1 ESV or ###### v2 NET
It took quite a bit of manual and python work to combine versions but works well with this plugin.

**Comment by kuchejak** [comment]
I did a little bit of research and it should be possible to support multiple versions if they are placed into different folders. Sadly, I still don't have enough free time to start working on it, but I should be able to look into it during October, maybe sooner.

I also intend to only add support for the copy command, but the link command should theoretically support full paths to files already.

**Comment by kuchejak** [comment]
I also want to make the plugin settings a bit more clear and organized before working on this issue.

**Comment by netfly** [comment]
Thanks for your great work ..... I use your plugin almost daily. It get's better and better. Awesome. 
Maybe I can help you with some tasks.

**Comment by kuchejak** [comment]
I'm slowly starting to work on this. There will be a few requirements for this to work though, so you can prepare your files in the meantime.

1. Each translation must be kept in its own folder - for example Bible/NIV and Bible/KJV.

2. All translations must use the same naming conventions for files - for example if the file is named "Gen 1" in NIV, it can not be "Gn 1" in KJV.

3. The structure of the files must be roughly the same, so that they all work with the same "Verse offset" and "Verse heading level" settings.

**Comment by kuchejak** [comment]
Multiple translation support is now available; update to version 1.4.0 to use it. It is quite basic, but I believe it will get the job done.
