### ISSUE TITLE
Correct shifted verses. Inherit separators.

### ISSUE THREAD

**Issue by An-qi-Zhang** [kuchejak/obsidian-bible-linker-plugin#2]
Hi, Kuchejak! Sorry to bother you again.

I found a few places available for perfection. I tried to modify the code to relieve your workload. However, I don't know how to use typescript well yet. I attached the main.js code as below. I am sorry for my inability to do a pull request.

### Input
Gen1:1
### Output
[[Gen1#2|Gen1,1-1]] **but actually Verse 2!** [[Gen1#2|]]

# Potential improvements
- The array variable **headings** may start from 0, instead of 1, like Python. Whenever there is headings[verseNumber/beginVerse/endVerse], you might want to -1 for the indexing.
- We can define bookChapter - **majorSeparator** - beginVerse - **minorSeparator** - endVerse. It would be great to pass down the separators in the input to the output, such as ":".
- If there is only 1 verse quoted, we may want "Gen1,1" instead of "Gen1,1-1".
- I don't see the necessity to append invisible links like [[Gen1#2|]] at the end, because Obsidian does not have backlink tracking for the headings (only the whole file), as I know of. If you see the value of keeping it, could you make it a toggle setting?

# Attempts to fix
### add parentheses to retrieve the major and minor separators
var oneVerseRegEx = new RegExp(/([a-zA-Z0-9\s.ěščřžýáíé]+)([,#.:;])(\d+)$/);
var multipleVersesRegEx = new RegExp(
	/([a-zA-Z0-9\s.ěščřžýáíé]+)([,#.:;])(\d+)\s*([-.=])\s*(\d+)$/
);

### catch up the major and minor separators
let majorSeparator;
let minorSeparator;

case oneVerseRegEx.test(userInput): {
				**const [_, matchedChapter, matchedMajorSeparator, matchedVerse] =
					userInput.match(oneVerseRegEx);**
				bookAndChapter = matchedChapter;
				**majorSeparator = matchedMajorSeparator;**
				beginVerse = Number(matchedVerse);
				endVerse = Number(matchedVerse);
				break;
			}
			case multipleVersesRegEx.test(userInput): {
				**const [
					_,
					matchedChapter,
					matchedMajorSeparator,
					matchedBeginVerse,
					matchedMinorSeparator,
					matchedEndVerse,
				] = userInput.match(multipleVersesRegEx);**
				bookAndChapter = matchedChapter;
				**majorSeparator = matchedMajorSeparator;**
				beginVerse = Number(matchedBeginVerse);
				**minorSeparator = matchedMinorSeparator;**
				endVerse = Number(matchedEndVerse);
				break;
			}

if (tFile) {
			return yield createLinkOutput(
...
				majorSeparator,
				minorSeparator,
...
			);

### get the correct range of verses
const headingLine = headings[verseNumber **- 1**].position.start.line;

### Delete or toggle the invisible links
for (let i = beginVerse; i <= endVerse; i++) {
		res += `[[${fileName}#${headings[i].heading}|]]`;
	}

### Achieve desired formats
...
		let res = settings.prefix;
		if (beginVerse == endVerse) {
			res += `[[${fileName}#${
				headings[beginVerse - 1].heading
			}|${fileName}${majorSeparator}${beginVerse}]] `;
		} else {
			if (settings.linkEndVerse) {
				res += `[[${fileName}#${
					headings[beginVerse - 1].heading
				}|${fileName}${majorSeparator}${beginVerse}]]`;
				res += `[[${fileName}#${
					headings[endVerse - 1].heading
				}|${minorSeparator}${endVerse}]] `;
			} else {
				res += `[[${fileName}#${
					headings[beginVerse - 1].heading
				}|${fileName}${majorSeparator}${beginVerse}${minorSeparator}${endVerse}]] `;
			}
		}
...

What this achieves is consistent with the input-output pairs below:

# A tentative test
## One verse
Gen1,1
[[Gen1#1|Gen1,1]] In the beginning God created the heavens and the earth.
Gen1:1
[[Gen1#1|Gen1:1]] In the beginning God created the heavens and the earth.

### Gen1,1-3
[[Gen1#1|Gen1,1]][[Gen1#3|-3]] In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, "Let there be light," and there was light.

### Gen1:1=3
[[Gen1#1|Gen1:1]][[Gen1#3|=3]] In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, "Let there be light," and there was light.

### Gen1,1-3
[[Gen1#1|Gen1,1-3]] In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, "Let there be light," and there was light.

### Gen1:1=3
[[Gen1#1|Gen1:1=3]] In the beginning God created the heavens and the earth. Now the earth was formless and empty, darkness was over the surface of the deep, and the Spirit of God was hovering over the waters. And God said, "Let there be light," and there was light.

# Thank you!

**Comment by kuchejak** [comment]
Hi, thank you for your feedback! Maybe just split them into multiple issues next time, so it is easier to reply/follow up on each one. Also please use code blocks for code so it is easier to read 😄

_The array variable headings may start from 0, instead of 1, like Python. Whenever there is headings[verseNumber/beginVerse/endVerse], you might want to -1 for the indexing._

- Yes, the array starts with index 0 just like in Python. The thing is, that most versions of markdown bible start files with some kind of non-verse heading, usually the name of the chapter. If you look to README.md there is a requirement for that. But I agree that it would be nice to add some setting for that so that people with different bible format can use the plugin as well. I could theoretically account for the offset automatically, I will look at it when I will have some spare time.

_We can define bookChapter - majorSeparator - beginVerse - minorSeparator - endVerse. It would be great to pass down the separators in the input to the output, such as ":"._

- That is actually how the linking worked in the first version - it would use the exact input for the output. The thing is, that for example "=" support is there only because I often switch between Czech and English keyboard layout, and "=" on Czech keyboard is where "-" is on English one, so I use it to fix my own mistake 😁 But I want the linking to be consistent, even when the input is not. 
- I could theoretically add a setting for that too, but it would very quickly lead to spaghetti code, so I would like to avoid it (at least for now).

_If there is only 1 verse quoted, we may want "Gen1,1" instead of "Gen1,1-1"._

- I know what you mean, but you can just use "Gen 1,1" as input, so I don't think that current behavior is problematic.

_I don't see the necessity to append invisible links like [[Gen1#2|]] at the end, because Obsidian does not have backlink tracking for the headings (only the whole file), as I know of. If you see the value of keeping it, could you make it a toggle setting?_
- Obsidian does not support it YET, I hope it will in the future because the ability to see where you linked a given verse (not just a passage) would be very useful and this is basically preparing for the future. Right now you should at least be able to find those links using the good old search tool. But adding setting for this should be easy, so I will try to do it sometime soon.

**Comment by kuchejak** [comment]
Implemented in version 1.1.0 (verse offset can be changed in settings)
