### ISSUE TITLE
[Feature/Enhancement Requests] Link with multiple language versions

### ISSUE THREAD

**Issue by allenzhao** [kuchejak/obsidian-bible-linker-plugin#25]
Hi kuchejak,

Thanks for your work! Is it possible to implement where I could insert multiple translations embedded links just as copying and linking? It is impossible to pick a version to embed links when just linking instead of copying. It would be great if there's also an option to embed multiple versions when using the link command, that would be great!

**Comment by kuchejak** [comment]
Hello,

I believe this would only be useful for a very small number of people because the copy command already works with multiple translations, embedding provides no clear benefits over copying for bible verses (as far as I know), and adding multiple translation support for the link command would be quite a complex and time consuming thing.

I recommend using the copy command instead.
