### ISSUE TITLE
FR: Use frontmatter alias as the book name

### ISSUE THREAD

**Issue by GovSat1** [kuchejak/obsidian-bible-linker-plugin#33]
When using an alias for each book, in the frontmatter of filename`Gen-01`, for example:

```
---
aliases
  - Genesis 1
---
```

An option to use the alias (or first alias) instead of the file name would improve the readability of references. So `[[Gen-01#v1|Gen 1:1-2]]` could be `[[Gen-01#v1|Genesis 1:1-2]]`

**Comment by kuchejak** [comment]
Hello, I'm not the biggest fan of this approach because I don't think that many people would use it (it requires a significant change to all Bible files to be useful).

There may be some way to specify the full name of the book in the future (not sure when though), but I'm not sure how it will work yet (see other issues).
