### ISSUE TITLE
Copy text from allready existing link

### ISSUE THREAD

**Issue by UrbanNinja1010** [kuchejak/obsidian-bible-linker-plugin#35]
Sometimes I allready have a link to a bibleverse, but I want to copy the text into my note.
It would be very nice to select an existing link, and have it automatically fill that into the dialog of the "copy and link Bible verses command"

**Comment by kuchejak** [comment]
Hi, I think this should be possible, but I'm not sure when people would use it. It would require you to have a link that is outside of any other text; otherwise, the copied verses would collide with the text around the link. And if you have a link outside of the other text, why not just copy the verses right away with the command?
