### ISSUE TITLE
Feature Request: Automatically Add Links to Bible Verses in Notes

### ISSUE THREAD

**Issue by didpeugeot** [kuchejak/obsidian-bible-linker-plugin#50]
Appreciate your plugin and its incredible flexibility!

I’d like to request a new feature that would allow to automatically scan a note and detect any Bible verse references (ex: John 3:16, Psalm 23:1, etc.). Upon detecting a reference, the plugin would then automatically convert those verse references into links (with a choice in Settings to make the link as either embedded, simple or quoted).

This would greatly benefit those of us who regularly include Bible verse references in their notes, such as during Bible study, talks notes, or personal journals, by automating the process of linking verses.

Just a suggestion. Thank you for reading it.

**Comment by kuchejak** [comment]
Hi! I'm glad you enjoy using the plugin. 

I understand your suggestion and it's potential usefulness, but this feature would be quite difficult to implement, because detecting a reference is not as easy as it may sound, especially when you consider that the plugin is used by people from all over the world so the names of the bible books differ and so does the notation used. 

It might be possible to use some preexisting library that would help with this, for example [this one](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser?tab=readme-ov-file), but they also mention several possible [caveats](https://github.com/openbibleinfo/Bible-Passage-Reference-Parser?tab=readme-ov-file#caveats).

It might be possible to work around those limitations, but I personally won't have time to dive into it any time soon. Sorry.
